[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true

padding.x = 4
padding.y = 8
dynamic_padding = true

[font]
normal.family = "Hack Nerd Font"
size = 12

[colors]
transparent_background_colors = true

[cursor]
style = { shape = "Block", blinking = "Always" }

